#!/bin/sh

volumeicon &
nm-applet &

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


# Start workspaces on 2 monitors.
bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor DVI-2 -d 6 7 8 9 10
bspc desktop -f 1


bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"
$HOME/.config/polybar/launch.sh
